- .cspell.json
- .github/workflows/test.yaml
- Cargo.lock
- Cargo.toml
- LICENSE
- README.md
- src/attribute.rs
- src/block.rs
- src/context.rs
- src/dialect.rs
- src/dialect_registry.rs
- src/identifier.rs
- src/lib.rs
- src/location.rs
- src/module.rs
- src/operation.rs
- src/operation_state.rs
- src/region.rs
- src/string_ref.rs
- src/type.rs
- src/utility.rs
- src/value.rs
- tools/setup.sh
- Use options for appropriate places.
- e.g. `argument`, `result`
- Refactor the operation state API.
> Support LLVM 15

- src/string_ref.rs
- src/type.rs
- src/value.rs
> String ref and value APIs

- src/error.rs
- src/execution_engine.rs
- src/ir/block.rs
- src/ir/operation.rs
- src/ir/type.rs
- src/lib.rs
- src/logical_result.rs
- src/pass/manager.rs
- src/utility.rs
> `Result<T, E>` as general failures

- src/context.rs
- src/ir/block.rs
- src/ir/block/argument.rs
- src/ir/operation.rs
- src/ir/operation/builder.rs
- src/ir/operation/result.rs
- src/ir/region.rs
The current impl of `Deref` is abuse.
Close #57.
> Use unsafe transmute for `Deref` of `*Ref`s

- .cspell.json
- Cargo.lock
- melior/Cargo.toml
- melior/src/string_ref.rs
fixes a TOCTOU race which made tests fail sometimes: https://en.wikipedia.org/wiki/Time-of-check_to_time-of-use
dashmap is the current go-to concurrent hashmap: https://github.com/xacrimon/dashmap
I found this because i was getting issues when running the GEP tests, they worked if i ran them alone, but since cargo executes tests in paralel, you can notice the bug there.
The contains key could be invalid at the time of insertion, which could produce buggy results, because its not atomic.
> Use dashmap instead of rwlock hashmap

- melior/src/context.rs
- melior/src/ir/operation.rs
- Should we adopt the original lifetime design of [Inkwell](https://thedan64.github.io/inkwell/inkwell/index.html)?
- But then, we need to distinguish `Context` and `ContextRef` in function signatures, or create another trait like `ContextRefLike`.
- Or, we can use `ContextRef` everywhere although it doesn't look Rust-ish...
> Unsafe context/operation dereferences

- melior/src/dialect/handle.rs
- melior/src/ir/type/id.rs
- melior/src/pass.rs
- melior/src/pass/external.rs
This PR implements support for the external pass API, enabling the creation of MLIR passes in Rust. It's still a bit rough on the edges, this is an early draft.
The main idea is as follows:
- Users of `melior` create a struct and implement the `ExternalPass` trait.
- When calling `create_external` on this struct, we use the external pass API to create a pass on the MLIR side.
- Using generic functions, callback functions are generated for this struct and passed to MLIR.
- Ownership of the Rust pass struct is conceptually moved to MLIR as a pointer to this struct is passed as `userData`, hence `Box::into_raw` is used.
- When the callbacks are called, we cast the `userData` pointer to the appropriate Rust struct and call a method of the `ExternalPass` trait.
- When MLIR decides to destruct …
> External pass

- melior/src/error.rs
- melior/src/ir/operation.rs
- melior/src/ir/operation/builder.rs
Added additional getters and setters for `Operation` such that you can get operands, results and attributes, and modify attributes. Most of these new functions are not strictly necessary, but they can be more convenient than the existing functions.
I'm using the `AttributeLike` trait such that any attribute-like type can be used. I wonder if we should also use this as generic return type for `Operation::attribute`?
I also created a `OperationOperand` type, but currently it is simply and alias for `Value`. Should `OperationOperand` be a more complex type like `OperationResult`, or should I remove `OperationOperand` and replace all its occurences with `Value`?
If I'm not mistaken, operands, results, successors and attributes can be borrowed by the builder, while ownership of regions is …
> Additional getters and setters for operation and builder

- macro/src/dialect/error.rs
- macro/src/dialect/operation.rs
- macro/src/dialect/operation/builder.rs
- macro/src/dialect/types.rs
Replaced calls to methods that may panic (`unwrap` and `expect`) with `Result`s, and did some minor refactoring.
> Remove panics from macro code

- macro/src/dialect/operation.rs
- macro/src/dialect/operation/accessors.rs
- macro/tests/operand.rs
- macro/tests/region.rs
- melior/src/error.rs
- melior/src/ir/operation.rs
As previously suggested in #274, I replaced the `.expect` with returning a `Result` in the operation accessors of ODS generated dialects.
I also added some variants to the `Error` enum to support this. The `Infallible` variant was added to allow using `TryInto` to convert `Attribute` into itself, such that we avoid needing to handle `Attribute` differently from `StringAttribute`, `IntAttribute`, etc. But if you prefer, I can change the macro code to deal with this case instead, I'm honestly not a big fan of my `Infallible` hack either.
> Return `Result` in accessors instead of panic

- macro/src/dialect/operation.rs
- macro/src/dialect/operation/accessors.rs
- macro/src/dialect/operation/builder.rs
Moved most `OperationField` fields to specific variants of the `FieldKind` enum and moved `param_type` and `return_type` to methods instead of determining them when constructing the `OperationField`.
I'm also refactoring the `Operation::from_def` method for a later PR, since it's way to large and hard to read. I'm replacing the `VariadicKind` updating with a more idiomatic `VariadicKindIter` that implements `Iterator`.
> Refactor OperationField

- melior/src/pass.rs
- melior/src/pass/external.rs
In #251, I overlooked to `mlirExternalPassSignalFailure` function. This requires a wrapper around `MlirExternalPass`, which is a CAPI pointer for the `ExternalPass` subclass of `::mlir::Pass` that represents any external pass and can expose some private methods from `Pass`.
I decided to call this wrapper `ExternalPassHandle`, since we are already using `ExternalPass` for the trait.
I originally made these changes a while ago when experimenting with extending the CAPI for analyses, but decided to make this PR, since `mlirExternalPassSignalFailure` is part of the MLIR CAPI already.
> Add support for `mlirExternalPassSignalFailure`

- melior/src/dialect/llvm.rs
- melior/src/dialect/snapshots/melior__dialect__llvm__tests__compile_intr_abs.snap
- melior/src/dialect/snapshots/melior__dialect__llvm__tests__compile_intr_bitreverse.snap
- melior/src/dialect/snapshots/melior__dialect__llvm__tests__compile_intr_bswap.snap
- melior/src/dialect/snapshots/melior__dialect__llvm__tests__compile_intr_ctlz.snap
- melior/src/dialect/snapshots/melior__dialect__llvm__tests__compile_intr_ctpop.snap
- melior/src/dialect/snapshots/melior__dialect__llvm__tests__compile_intr_cttz.snap
- melior/src/dialect/snapshots/melior__dialect__llvm__tests__compile_zext.snap
Btw i found out about the ods, its pretty neat!
Although i haven't found these intrinsics in the ods.
> add some llvm intrinsics

- melior/src/context.rs
> Refactor `ContextRef`

- macro/src/dialect/operation/builder.rs
- macro/src/operation.rs
- melior/src/dialect/arith.rs
- melior/src/dialect/cf.rs
- melior/src/dialect/func.rs
- melior/src/dialect/index.rs
- melior/src/dialect/llvm.rs
- melior/src/dialect/memref.rs
- melior/src/dialect/scf.rs
- melior/src/error.rs
- melior/src/ir/block.rs
- melior/src/ir/module.rs
- melior/src/ir/operation.rs
- melior/src/ir/operation/builder.rs
- melior/src/ir/operation/result.rs
- melior/src/ir/value.rs
- melior/src/lib.rs
> Catch operation build failure

- melior/src/context.rs
- melior/src/string_ref.rs
- Remove string cache
- Fix
- Fix
> Remove string cache

- melior/src/ir/type/mem_ref.rs
If you make a memref type with i64::MAX - 1 you will see the output shows memref<-1xTYPE>
also the pointer in mlir-sys is a *i64
By the way, do you know how to make a memref like memref<?xTYPE> ?
> memref dimensions should be i64

- melior/src/ir/attribute.rs
- melior/src/ir/attribute/bool.rs
This was motivated by my attempt to build a JIT compiler that links with existing rust code. This requires 
`attributes { llvm.emit_c_interface }` to invoke the MLIR compiled function.
I am very new to MLIR, so please double check this PR. 
-----
**Edit:** Looks like I did made a mistake for my usecase. I should have been using the `UnitAttr`. 
Regardless, hopefully this PR is still useful.
> Add Bool Attribute

- Cargo.lock
- macro/Cargo.toml
comrak provides a lot of features that are not used here, disable them to remove a bunch of dependencies.
> Disable default features from comrak

- melior/src/string_ref.rs
Building `melior` for Linux ARM doesn't work because of FFI types. This PR fixes this by making the compiler select the target pointer type automatically. It's the same issue we had in `tblgen-rs-alt`.
> Fix aarch64 linux build.

- melior/src/ir/operation.rs
feat: add location method for the operation structure
> feat: add location method for the operation structure

- melior/src/context.rs
I am one of the users of Melbourne and have found that ContextRef does not have a publicly available method to convert to `&'c Context`, so I've opened this PR to add the `to_ref` function for the context like the `OperationRef` does at https://github.com/raviqqe/melior/blob/main/melior/src/ir/operation.rs
> feat: add to_ref and Deref functions for the context

- Cargo.lock
- macro/Cargo.toml
- macro/src/dialect/operation/attribute.rs
- macro/src/utility.rs
- melior/Cargo.toml
- **Use `std::cell::sync::LazyCell`**
- **Fix**
> Remove unused dependencies

- macro/src/dialect/input.rs
- macro/src/dialect/operation.rs
- macro/src/dialect/operation/attribute.rs
- macro/src/dialect/operation/builder.rs
- macro/src/dialect/operation/builder/type_state.rs
- macro/src/dialect/operation/region.rs
- macro/src/dialect/operation/successor.rs
- macro/src/dialect/type.rs
- macro/src/dialect/utility.rs
- melior/src/context.rs
- melior/src/diagnostic.rs
- melior/src/dialect.rs
- melior/src/dialect/llvm/load_store_options.rs
- melior/src/ir/affine_map.rs
- melior/src/ir/attribute.rs
- melior/src/ir/block.rs
- melior/src/ir/block/argument.rs
- melior/src/ir/identifier.rs
- melior/src/ir/location.rs
- melior/src/ir/module.rs
- melior/src/ir/operation.rs
- melior/src/ir/operation/builder.rs
- melior/src/ir/operation/result.rs
- melior/src/ir/region.rs
- melior/src/ir/type.rs
- melior/src/ir/value.rs
- melior/src/pass/external.rs
- melior/src/pass/manager.rs
- melior/src/pass/operation_manager.rs
- melior/src/string_ref.rs
Should fix the new lint ci errors due to rust 1.83.0 new clippy lints
On rust 1.83.0 with clippy `cargo clippy -- -D clippy::nursery -A clippy::use_self`
There are some more places where i could add const (in mut self places) but thats from 1.83.0 itself and i dont know if you are ok with setting the MSRV to it, so i didnt add those.
> Cleanup aided by clippy

- cspell.json
- macro/src/dialect.rs
- melior/src/dialect/ods.rs
- melior/src/utility.rs
This fixes support for the following dialects in ODS like IRDL
Fixes #540 
This pr includes #639
> Fix ods include paths in macro, allowing for new dialects

- Cargo.lock
- macro/Cargo.toml
- macro/src/dialect.rs
- macro/src/dialect/input.rs
- macro/src/dialect/input/input_field.rs
- macro/tests/operand.rs
- macro/tests/region.rs
- melior/src/dialect/ods.rs
- melior/src/ir/operation.rs
This PR refactors dialect macro input.
- Depends on https://github.com/mlir-rs/tblgen-rs-alt/pull/18
> Refactor dialect macro input

- macro/tests/region.rs
- melior/src/dialect/arith.rs
- melior/src/dialect/cf.rs
- melior/src/dialect/func.rs
- melior/src/dialect/index.rs
- melior/src/dialect/llvm.rs
- melior/src/dialect/memref.rs
- melior/src/dialect/ods.rs
- melior/src/dialect/scf.rs
- melior/src/ir.rs
- melior/src/ir/attribute/attribute_like.rs
- melior/src/ir/block.rs
- melior/src/ir/block/block_like.rs
- melior/src/ir/module.rs
- melior/src/ir/operation.rs
- melior/src/ir/region.rs
- melior/src/ir/region/region_like.rs
- melior/src/ir/type/type_like.rs
- melior/src/ir/value/value_like.rs
- melior/src/lib.rs
- melior/src/pass/external.rs
> `RegionLike` trait

- melior/src/ir/operation.rs
- melior/src/ir/operation/operation_like.rs
This exposes mlir_sys::mlirOperationWalk as OperationLike::walk, OperationLike::walk_pre, & OperationLike::walk_post
There are `#[test]`s for `walk_pre` & `walk_post`
This addresses #707
> Introduce OperationLike::walk
