mlir-rs/melior

.cspell.json, src/attribute.rs, src/type.rs, src/type/id.rs, src/type/id/allocator.rs
=> Attribute API

src/dialect/llvm.rs, src/dialect/llvm/type.rs, src/ir/identifier.rs, src/lib.rs, src/logical_result.rs, src/string_ref.rs, src/utility.rs
=> Top-level namespace

src/pass/manager.rs, src/pass/transform.rs, src/utility.rs
=> Add pass registration functions

src/ir/block.rs, src/ir/operation.rs, src/ir/type.rs, src/ir/value.rs
=> Comprehensive `Debug` impls

LICENSE, src/dialect/llvm/type.rs, src/ir/location.rs, src/ir/type/type_like.rs
- [edg-l/melior-next](https://github.com/edg-l/melior-next)
=> Port part of `edg-l/melior-next`

melior/src/ir/attribute.rs, melior/src/ir/attribute/array.rs, melior/src/ir/attribute/dense_i32_array.rs, melior/src/ir/attribute/dense_i64_array.rs, melior/src/ir/operation.rs
=> Array attribute

melior/src/ir/attribute/dense_elements.rs
=> Fix dense elements attribute test

.cspell.json, melior/src/dialect/func.rs, melior/src/ir/attribute.rs, melior/src/ir/attribute/array.rs, melior/src/ir/attribute/dense_elements.rs, melior/src/ir/attribute/dense_i32_array.rs, melior/src/ir/attribute/dense_i64_array.rs, melior/src/ir/attribute/flat_symbol_ref.rs, melior/src/ir/attribute/type.rs, melior/src/ir/block.rs, melior/src/ir/module.rs, melior/src/ir/operation.rs, melior/src/ir/operation/builder.rs, melior/src/ir/operation/result.rs, melior/src/ir/type.rs, melior/src/ir/value.rs, melior/src/pass/manager.rs
fixes #188 
i also fixed some tests using unregistered dialects (catched with llvm assertions on)
=> fix dense array using the wrong len method and #188

macro/src/parse.rs, melior/src/context.rs, melior/src/diagnostic/handler_id.rs, melior/src/dialect/handle.rs, melior/src/dialect/registry.rs, melior/src/ir/block.rs, melior/src/ir/identifier.rs, melior/src/ir/location.rs, melior/src/ir/module.rs, melior/src/ir/operation.rs, melior/src/ir/operation/printing_flags.rs, melior/src/ir/type/id.rs, melior/src/logical_result.rs, melior/src/pass.rs, melior/src/pass/operation_manager.rs, melior/src/string_ref.rs
The LogicalResult pub is fine because the module itself is private.
=> apply some clippy::nursery suggestions

melior/src/ir/value.rs
=> fix display unregistered, allow unregistered dialects

melior/src/dialect/cf.rs, melior/src/dialect/llvm.rs, melior/src/dialect/scf.rs, melior/src/ir/attribute.rs, melior/src/ir/block.rs, melior/src/ir/block/argument.rs, melior/src/ir/module.rs, melior/src/ir/operation.rs, melior/src/ir/operation/builder.rs, melior/src/ir/operation/result.rs, melior/src/ir/type.rs, melior/src/ir/value.rs, melior/src/ir/value/value_like.rs, melior/src/lib.rs, melior/src/macro.rs
=> Fix `Value` lifetime

melior/src/dialect/llvm/type.rs, melior/src/ir/block.rs, melior/src/ir/location.rs, melior/src/ir/operation/builder.rs, melior/src/ir/type/function.rs, melior/src/ir/type/tuple.rs, melior/src/utility.rs
=> Remove `into_raw_array` function

melior/src/dialect/func.rs, melior/src/dialect/snapshots/melior__dialect__func__tests__compile_external_function.snap, melior/src/dialect/snapshots/melior__dialect__func__tests__compile_external_function.snap.new
Close #291.
- https://mlir.llvm.org/getting_started/Faq/#whats-with-op-symbol-declaration-cannot-have-public-visibility
=> Test external `func` operation

melior/src/ir/location.rs
=> add call_site location

macro/src/dialect/generation.rs, macro/src/dialect/generation/attribute_accessor.rs, macro/src/dialect/operation/attribute.rs
- **Refactor attribute accessor error handling**
=> Refactor attribute accessor macros

macro/src/dialect/generation/attribute_accessor.rs
- **Remove more `context` arguments**
=> Remove more `context` arguments

melior/src/dialect.rs, melior/src/string_ref.rs
=> Remove some todos

macro/src/dialect/generation/operation_builder.rs, melior/src/pass/external.rs
=> Remove "new" in documentation

macro/src/dialect/generation/operation_builder.rs
=> Refactor builder logic

macro/src/dialect/generation.rs, macro/src/dialect/generation/element_accessor.rs, macro/src/dialect/generation/operand_accessor.rs, macro/src/dialect/generation/region_accessor.rs, macro/src/dialect/generation/result_accessor.rs, macro/src/dialect/generation/successor_accessor.rs
=> Refactor accessors

macro/src/dialect/generation.rs, macro/src/dialect/generation/element_accessor.rs, macro/src/dialect/generation/operation_builder.rs, macro/src/dialect/operation.rs
- **Update operation documentation**
=> Update operation documentation

macro/src/dialect/generation/operation_builder.rs
=> Refactor variable names

macro/src/dialect/operation.rs
=> Improve articles

melior/src/dialect/ods.rs
=> LLVM intrinsic dialect

.github/workflows/document.yaml
- **Update document workflow**
=> Update document workflow

melior/src/dialect/ods.rs, melior/src/dialect/snapshots/melior__dialect__ods__tests__addf.snap, melior/src/dialect/snapshots/melior__dialect__ods__tests__addf_builder.snap
- **Fix**
- **Fix**
- **Fix**
- **Fix**
- **Fix**
- **Fix**
=> Fix `add_*` method calls

.github/workflows/document.yaml
- **Revert "Copy documentation directory first (#463)"**
- **Fix permissions**
=> Fix documentation deployment

melior/src/ir/module.rs, melior/src/ir/operation.rs
=> `OperationRefMut`

melior/src/ir/attribute/float.rs, melior/src/ir/attribute/integer.rs
- **More values from attributes**
- **Fix**
=> Add more attribute accessors

melior/src/ir/type/type_like.rs
- **Get dialect from type**
- **Fix**
=> Get dialect from types

melior/src/dialect/memref.rs, melior/src/dialect/snapshots/melior__dialect__memref__tests__subview.snap, melior/src/dialect/snapshots/melior__dialect__memref__tests__view.snap
I am not entirely convinced this is the optimal API for `subview` & and very much open to suggestions.
=> Add memref subview & view functions

.cspell.json, melior/src/dialect/ods.rs
There are some dialects that fail to parse with the macro, and i don't know much about the inner workings of the macro, ill try to look into it maybe
=> Add more dialects to ods

melior/src/dialect/llvm.rs
https://mlir.llvm.org/docs/Dialects/LLVM/#llvmmlirzero-llvmzeroop
=> change the way a nullptr is made

melior/src/ir/operation/builder.rs, melior/src/pass/external.rs
- **Fix**
- **Fix**
- **Fix**
- **Fix**
- **Fix**
=> Fix linting

melior/src/pass/manager.rs
=> Add PassManager from/to raw methods

melior/src/utility.rs
=> Add load_irdl_dialects

macro/src/dialect/operation/builder/type_state.rs, melior/src/ir/block.rs, melior/src/ir/block/block_like.rs, melior/src/ir/region.rs, melior/src/ir/region/region_like.rs
Inheriting the `Copy` trait is like a hack...
=> Fix owned `*Like` traits
